services:
  - type: web
    name: parejiya-parivar-backend
    env: node
    buildCommand: npm install && npx prisma generate && tsc
    startCommand: node dist/src/server.js
    envVars:
      - key: NODE_ENV
        value: production
