services:
  - type: web
    name: your-backend-name
    env: node
    buildCommand: npm install && npx prisma generate && tsc
    startCommand: node dist/server.js
    envVars:
      - key: NODE_ENV
        value: production
